trigger:
- main

pool:
  vmImage: windows-latest

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Microsoft-Azure-5(e9897c49-eaca-4f56-b924-1d77a1b6a395)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group what-if \
               --resource-group rg-arm-devops \
               --name rollout01 \
               --template-file azuredeploy.json \
               --parameters azuredeploy.parameters.json

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Microsoft-Azure-5(e9897c49-eaca-4f56-b924-1d77a1b6a395)'
    subscriptionId: 'e9897c49-eaca-4f56-b924-1d77a1b6a395'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'rg-arm-devops'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    deploymentMode: 'Incremental'